import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footter";
import CustomCursor from "@/components/CustonCurrson";

export const metadata = {
  title: "mindsynccon.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Header/>
        <CustomCursor/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
